FROM hashicorp/vault-radar:latest

USER root
RUN apk add --no-cache curl ca-certificates
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
RUN update-ca-certificates
CMD ["vault-radar", "agent", "exec"]