apiVersion: v1
kind: Secret
metadata:
  name: vault-radar-secrets
  namespace: vault-radar
  labels:
    app: vault-radar-agent
type: Opaque
data:
  HCP_CLIENT_SECRET: cHpfbTlNTnVIVG1haXRnRC1wLVlwYzdFRmV3bjBYaVpucVJiZmVDZDQtbWxpNzRHOTFLb3hHR1BNZWQ5ZnR1aQ==
  VAULT_RADAR_GIT_TOKEN: Z2hwX1V6c09ZRVE1UUZpU3BiN0FvcTN3cEJ0WDZ0WEl2NjAyNHlhbA==
  CONFLUENCE_TOKEN: TmpNMU16STNNVE15TURFMU9ybFNOdkNFc0xSV0RDcU0rbFExVjl5cU9Kemo=
  JIRA_TOKEN: T1RNME5qUXpOVE01TURNek9nNFFVMDFKMEQvNElSZWlZODVqbFNHeVlEU3E=
